/** Declaration file generated by dts-gen */
declare module 'password-prompt' {
  interface Options {
    method?: 'hide' | 'mask' | string;
    required?: boolean;
    default?: string;
  }
  function password_prompt(ask: string, options?: Options): Promise<string>;
  export = password_prompt;
}
